# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: production
remote_data_prefix: "https://gsa.github.io/sdg-data-usa/prod"
# permalink: /news/:year/:month/:day/:title.html

# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#GSA/sdg-data-usa/edit/develop/data-wide/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#GSA/sdg-data-usa/edit/develop/meta/[id].md

# Automatically create indicator pages, goal pages, and other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal
create_pages: true

analytics:
  ga_prod: 'UA-42145528-4'

###################################################################################################
email_contacts:
  questions: mbx.omb.oirasdgs@omb.eop.gov
  suggestions: mbx.omb.oirasdgs@omb.eop.gov
  functional: datagov@gsa.gov
###################################################################################################

# Build settings
markdown: kramdown

# Travis Support
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README.md

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: US
  adjective: US

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

footer_menu:
  - path: /contact
    translation_key: menu.contact_us
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# The list of languages that are translated. The first one is the default.
languages:
  - en
  - es
  - fr

# Point to remote location of goal images.
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

remote_theme: open-sdg/open-sdg@1.1.0
