name: QA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'

jobs:
  qa:
    name: Test HTML Links
    uses: gsa/data.gov/.github/workflows/static-site-qa-template.yml@data-gov-static-site-templates
